apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: foo3
  janus-idp.io/tekton: foo3
  backstage.io/kubernetes-id: foo3
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: foo3
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
