apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: foo3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: foo3 
  name: foo3
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: foo3 
